build:
  image: node:0.10
  commands:
    - cd hubots/hubot-baronbogo
    - npm -d install
    - npm test
    - cd ../hubot-gitsy
    - npm -d install
    - npm test
publish:
  npm:
    when:
      event: tag
    username: $$NPM_USERNAME
    password: $$NPM_PASSWORD
    email: $$NPM_EMAIL
    folder: hubots/hubot-baronbogo

  npm:
    when:
      event: tag
    username: $$NPM_USERNAME
    password: $$NPM_PASSWORD
    email: $$NPM_EMAIL
    folder: hubots/hubot-gitsy


  docker:
    when:
      event: tag
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: rocketchat/hubot-baronbogo
    file: hubots/hubot-baronbogo/Dockerfile
    tag: $$TAG

  docker:
    when:
      event: tag
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: rocketchat/hubot-gitsy
    file: hubots/hubot-gitsy/Dockerfile
    tag: $$TAG
